/*
 Generated by typeshare 1.4.0
*/

export interface RegisterCredentials {
	username: string;
	email: string;
	password: string;
}

export interface LoginCredentials {
	email: string;
	password: string;
}

export interface AddComment {
	content: string;
}

export interface Comment {
	author: string;
	content: string;
}

export interface Product {
	name: string;
	price: number;
	rating?: number;
	image?: string;
}

export interface Rating {
	username: string;
	rating: number;
}

export interface Rate {
	rating: number;
}

export interface AddProduct {
	name: string;
	price: number;
	image?: string;
}

